### ISSUE TITLE
Compilier Error on v1.3

### ISSUE THREAD

**Issue by epwolf** [FalsinSoft/QtAndroidTools#11]
\Qt\Qt5.9.9\5.9.9\android_armv7\mkspecs\android-g++ -o QtAndroidTools.obj ..\QtAndroidTools\QtAndroidTools.cpp
In file included from ..\QtAndroidTools\QtAndroidTools.cpp:26:0:
..\QtAndroidTools\QAndroidAppPermissions.h:52:52: error: 'PermissionResultMap' in namespace 'QtAndroid' does not name a type
     void RequestPermissionResults(const QtAndroid::PermissionResultMap &ResultMap);
                                                    ^
..\QtAndroidTools\QAndroidAppPermissions.h:53:56: error: 'PermissionResultMap' in namespace 'QtAndroid' does not name a type
     QVariantList ConvertToVariantList(const QtAndroid::PermissionResultMap &ResultMap);
                                                        ^
make: *** [QtAndroidTools.obj] Error 1
make: *** Waiting for unfinished jobs....
17:40:48: 进程"D:\Qt\Android\android-ndk-r17c\prebuilt\windows\bin\make.exe"退出，退出代码 2 。
Error while building/deploying project QtAndroidToolsDemo (kit: Android for armeabi-v7a (Clang Qt 5.9.9 for Android ARMv7))
When executing step "Make"
17:40:48: Elapsed time: 00:07.

**Comment by FalsinSoft** [comment]
At first, please note the library has been developed using the latest versions of Qt and use with older versions is not guaranteed (like 5.9 in your case). Said that, the error is clear, are you using standard Qt version or some customized version for embedded device? Additional information about the environment generating this error would be necessary for a better comprension of the problem, just copy and paste the error log only is not very helpful...

**Comment by epwolf** [comment]
Thaks. After I change some code, it worked good now on Qt5.9.9.
