### ISSUE TITLE
Is Qt5.14.x supported?

### ISSUE THREAD

**Issue by shujaatak** [FalsinSoft/QtAndroidTools#15]

**Comment by FalsinSoft** [comment]
Yes, latest commit contain all the required changes to compile using Qt 5.14.2

**Comment by shujaatak** [comment]
Going to check it out.

**Comment by shujaatak** [comment]
Is it using AdMob with Firebase or without Firebase? Sorry if it feels a silly question.

**Comment by FalsinSoft** [comment]
Without. Firebase library size is quite big, the library use only the system AdMob api with the minimun of java code for interface with Qt..

**Comment by shujaatak** [comment]
Any hints how can I use Firebase C++ SDK in Qt?

**Comment by demiantres** [comment]
Check this project: https://github.com/Larpon/QtFirebase

**Comment by FalsinSoft** [comment]
I was about to suggest the same project. However I never tried it than I can not guarantee if it work as expected.

**Comment by shujaatak** [comment]
@demiantres  I tried that project with Qt5.14.2 but I am getting strange issues although I have followed the instructions very carefully, I don't know whether Qt5.14.2 is not supported or I'm missing something.

**Comment by FalsinSoft** [comment]
I think in case of problem you should open an issue in the project page itself for have help.

**Comment by demiantres** [comment]
I have been using the project with Qt 5.13.2 without major problems. If you have problems then please post a bug report in the QtFirebase project.

**Comment by shujaatak** [comment]
OK.
I am closing this issue as QtAndroidTools already supports Qt5.14.2.
