### ISSUE TITLE
java.lang.NullPointerException in  com.google.android.vending.expansion.downloader.impl.DownloaderService

### ISSUE THREAD

**Issue by FranckRICHARD01** [FalsinSoft/QtAndroidTools#16]
Hello and thank you for QtAndroid Tools which allows to simplify the management of Google Play functions with Qt!

I sometimes get an error in the Play Console and I get a **java.lang.NullPointerException**: which **appeared in the com.google.android.vending.expansion.downloader.impl** module.

How do I fix this?

With thanks,

Francky033

**java.lang.NullPointerException:** 
  at javax.crypto.spec.PBEKeySpec.<init> (PBEKeySpec.java:115)
  at com.google.android.vending.licensing.AESObfuscator.<init> (AESObfuscator.java:59)
  **at com.google.android.vending.expansion.downloader.impl.DownloaderService$LVLRunnable.run (DownloaderService.java:730)**
  at android.os.Handler.handleCallback (Handler.java:790)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6626)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:811)

**Comment by FalsinSoft** [comment]
Hi
Never see such error. I use the same library for download extension file for one of my apps and it always worked well. When you say "sometimes" mean with which frequency you see the error? You use the emulator and a physical device for test?

**Comment by FranckRICHARD01** [comment]
Everything works well when I test on physical devices!
It's the Google Console Play that informs me of this exception which is always the same and affects about twenty devices each month at the moment of installation. All versions of Android seem to be affected.
On the other hand, I noticed today a possible error from me. I was using the default salt as defined in the demo:

QtAndroidApkExpansionFiles.salt = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20];

Could this cause the AESObfuscator function to fail?

I have just corrected my application to check if there is an effect ...

Thank you!

Francky033

**Comment by FalsinSoft** [comment]
I don't think the salt sequence could be the problem (in any case it's always better to chage for better security). These devices reporting the error never work or the error come up sometimes but after a retry the download work well?

**Comment by FranckRICHARD01** [comment]
I have no idea about that. I don't know if the download will be successful when the program is restarted. But the problem seems coming from the variable salt = null. How can this be explained?

**Comment by FalsinSoft** [comment]
Maybe here?

```
DownloadResult = m_JavaApkExpansionFiles.callMethod<jint>("startDownloader",
                                                          "(Ljava/lang/String;[B)I",                                                                                                                                    QAndroidJniObject::fromString(m_Base64PublicKey).object<jstring>(),
                                                          SALT
                                                           );
JniEnv->DeleteLocalRef(SALT);
```

SALT array is deallocated immediately after the call, maybe java code is not executed immediately and the data is not available? I don't know if JNI pass params by value or by reference...

**Comment by FranckRICHARD01** [comment]
Yes. It might be necessary to set a delay before destroying SALT.
Moreover, during the download, I use QApplication::processEvents(); to process the others signals. Maybe this is a problem with this DeleteLocalRef ?

**Comment by FalsinSoft** [comment]
Download is asyncronous, why use QApplication::processEvents()?

**Comment by FranckRICHARD01** [comment]
Yeah. It's probably a mistake. I'll check it out. Thanks anyway for your observations and for QtAndroidTools!

**Comment by zlutor** [comment]
Ooo, delays, the good old delays. The most dangerous silent killer of all... ;)

**Comment by FranckRICHARD01** [comment]
Yes ;)

**Comment by FalsinSoft** [comment]
What about this issue, have you resolved it?

**Comment by FalsinSoft** [comment]
Cause I didn't receive any reply I'll consider this issue as closed. Reopen it if the problem still occurs.

**Comment by FranckRICHARD01** [comment]
Hello and sorry to answer so late. I forgot your message.

Here's the situation:
After checking, I didn't use any QApplication::processEvents(), or a delay in the part of the program that downloads the obb.

I'm just waiting until the program has finished downloading the obb before closing the qml box.

I left my program on Google Play for three days after setting a custom SALT and I had no bugs during that time. Is there a cause and effect link, I don't really know...
I will put my program back on Google Play in the next few days. That will be the opportunity to confirm things.

Thanks for the support !

Francky033
