### ISSUE TITLE
Demo is not Working, Please Help..!!

### ISSUE THREAD

**Issue by rajeabhilash** [FalsinSoft/QtAndroidTools#20]
Hello, There there is an error while running the demo code you provided. I need some of the tools from so badly.. Please Help..!!
Error encountered When it is copying **google** folder from tools to android **res/com/google** folder..Don't Know what to do..!!
```
The system cannot find the path specified.
make: *** [make_tools_dir] Error 1
make: *** Waiting for unfinished jobs....
make: *** [copy_tools] Error 1
make: *** [copy_apk_expansion_files] Error 1
The system cannot find the file specified.
The system cannot find the file specified.
Invalid number of parameters
make: *** [copy_google] Error 4
14:30:47: The process "C:\Users\rajea\AppData\Local\Android\ndk\prebuilt\windows-x86_64\bin\make.exe" exited with code 2.
Error while building/deploying project QtAndroidToolsDemo (kit: Android for armeabi-v7a (Clang Qt 5.12.6 for Android ARMv7))
When executing step "Make"
```

**Comment by FalsinSoft** [comment]
Are you compiling the latest committed version?

**Comment by rajeabhilash** [comment]
Yes, I just downloaded and Trying to Compile but this getting this error..!! Is it necessary to change java packages in QtAndroidTools or use it as it is..???

**Comment by FalsinSoft** [comment]
Do you compile on Windows or Linux? There is no need for any changes, the demo app should compile as it is.

**Comment by FalsinSoft** [comment]
I didn't receive reply, do you still need help? If I will not receive reply I'll consider this issue as closed...

**Comment by rajeabhilash** [comment]
> Do you compile on Windows or Linux? There is no need for any changes, the demo app should compile as it is.

Sir compiled it on Windows 10, with Qt Creator 4.11.0 (community version).
Sir, I need to launch product within a month I really need it to be working..!!

**Comment by FalsinSoft** [comment]
Remember Qt Creator on Windows have a problem with long path. Try to make the compilation path shorter like this:

c:\myproject\builddirectory

**Comment by FalsinSoft** [comment]
Have you fixed the problem?
