### ISSUE TITLE
Feature Request: EU GDPR User Consent Form

### ISSUE THREAD

**Issue by tom-hines** [FalsinSoft/QtAndroidTools#23]
We are now required to get user consent for both personalized and non-personalized ads for users in the EU and California. Google has two java SDKs that implement this, a deprecated Consent SDK and the new User Messaging Platform SDK. This would be a significant development effort but this project seems like a good place for it. Any chance of it happening? Thanks.

Links:
[EU User Consent Policy](https://www.google.com/about/company/user-consent-policy/)
[AdMob policy](https://support.google.com/admob/answer/7666519)
[Consent SDK](https://developers.google.com/admob/android/eu-consent)
[UMP SDK](https://developers.google.com/admob/ump/android/quick-start)

**Comment by FalsinSoft** [comment]
Hi
I gave it a quick read as I'm pretty busy right now but the documentation surprised me a bit. It's the developer who have to show the form and keep safe somewhere the user choice? And if the user does not authorize anything is not possible to show banner?

**Comment by tom-hines** [comment]
Yes, it is the developer's responsibility to get and remember consent, and make it available if the user wants to change it.  It's up to the developer to decide what to do if the user rejects ads.  If the user picks non-personalized ads, we have to pass a parameter to the Google Mobile Ads SDK (`npa=1`).

The SDKs are available now but I don't know what the deadline is for us to comply.

**Comment by FalsinSoft** [comment]
Reading the documentation better it seem there are two authorization to ask, one for store cookies and another for the use of personal data for ads personalization. Can you confirm? But standard AdMob use cookies?

**Comment by tom-hines** [comment]
I think cookies are just used by websites.  For mobile devices I think AdMob just uses an advertising_id, but I don't know.  The SDKs provide a single consent form that fulfills the requirement.

**Comment by FalsinSoft** [comment]
Unfortunately it seem use cookies as written here:

[Personalized and non-personalized ads](https://support.google.com/admob/answer/7676680)

That's mean if the user don't give permission for cookies theoretically ads should not be showed, do you understand the same?

**Comment by tom-hines** [comment]
The consent form gives 3 choices:

1. Personalized ads (maximum data collection)
2. Non-personalized ads (minimum data collection)
3. No ads (no data collection)

If the user picks option 3 then we can't show ads.

**Comment by FalsinSoft** [comment]
Where did you find this information about form? Can you link me there?

**Comment by tom-hines** [comment]
[Consent SDK Form](https://github.com/googleads/googleads-consent-sdk-android/blob/master/consent-library/src/main/assets/consentform.html)

There's a picture of it on this page:
[Pic](https://developers.google.com/admob/android/eu-consent#collect-consent)

**Comment by FalsinSoft** [comment]
There still are some points I don't have very clear but I'll try to add a tool to the library for manage consent form. However I don't know when but I hope soon...

**Comment by tom-hines** [comment]
Thank you. Would've been easier on us native devs if Google had given us a web service implementation. Let me know if I can help in any way.

**Comment by FalsinSoft** [comment]
Hi
I added the tool for manage consent form (using UMP SDK) in the last commit. It's not documented yet because I would to know your opinion about. Currently I provided only one function named _showConsentFormIfRequired()_ doing all the job. A signal return the final result (error or form closed). I already tested with one of my app and it work (I still have to know how to manage consent form in different languages). Please, give it a try and keep me informed about your comments or suggestions.
Thank you

**Comment by tom-hines** [comment]
Thank you!  I'll try to take a look at it this week.

**Comment by FalsinSoft** [comment]
Hi
Did you try the new tool? What do you think about? It seem very strange to me but in the google Funding Choices UI is possible to enable only one form with specific language. It seem there is no possibilties to have multiple forms in different languages...

**Comment by tom-hines** [comment]
I've been busy with another project so I haven't had a chance to test it yet, but I did look at the code and it looks good. I'm glad you went with the new UMP instead of the old Consent SDK. I thought I read somewhere that Google has forms for each language if you use the default form, but I can't find it now. I'll try to test it soon.

**Comment by FalsinSoft** [comment]
Just committed the final version of the tool and updated the documentation too. I changed something for a better use. Please try it and close this issue if you think is ok now.

**Comment by tom-hines** [comment]
My Qt Android environment is hopelessly messed up now, so I wasn't able to test it. But I did look at the code and it looks good. Thank you!
