### ISSUE TITLE
the services arguments must be set for a service not run in an external library

### ISSUE THREAD

**Issue by FranckRICHARD01** [FalsinSoft/QtAndroidTools#24]
Since the upgrade to QtCreator 4.13, I get an error message when I want to save my AndroidManifest.xml

It is the management of the apk expansion downloader service that causes a problem.

<android service:name="com.google.android.vending.expansion.downloader.impl.DownloaderService" android:enabled="true"/>
<receiver android:name="com.google.android.vending.expansion.downloader.impl.DownloaderService$AlarmReceiver" android:enabled="true"/>

Qt creator shows me the error message: "Cannot save when there are invalid services".

![20200901](https://user-images.githubusercontent.com/65286120/91869592-600d4580-ec76-11ea-9db6-6f4e88aa6130.jpg)

There's an exclamation point that says "the services arguments must be set for a service not run in an external library".

When I check "run in external process", it still asks me "process name" and "process argument".

What should I put?

Thanks!

**Comment by FalsinSoft** [comment]
Hi
Unfortunately is a bug of new Qt Creator as reported here:

https://bugreports.qt.io/browse/QTCREATORBUG-24557

We have to wait for a fix or manually edit the AndroidManifest.xml file...

**Comment by FalsinSoft** [comment]
New version of Qt Creator 4.13.1 has been released with thig bug fixed
