### ISSUE TITLE
QtAndroidTools for CMake

### ISSUE THREAD

**Issue by ssakone** [FalsinSoft/QtAndroidTools#29]
When are you going to make, CMakeFile Support ? :)

**Comment by FalsinSoft** [comment]
Hi
I use Qt Creator under Windows than, currently, no need of CMakeFile but I can add it, there is a pull request about it also. However how to test if work correctly?

**Comment by ssakone** [comment]
Oh i see the pull, i can test it and show you.

you need to create a new project in QtCreator as cmake project not qmake, and include the new cmake support of pull request

**Comment by FalsinSoft** [comment]
Hi
Just pushed CMake project files. Please try it and if is correct close this issue.
Thank you

**Comment by ssakone** [comment]
no problem,  i make this today

**Comment by ssakone** [comment]
I make some basic Test with new cmake implementation, its work fine (i add some line in gradle.properties and build.gradle
![image](https://user-images.githubusercontent.com/39985611/111864437-d181bc80-8958-11eb-90f9-3cc6ed3414a7.png)

**Comment by FalsinSoft** [comment]
If you think your changes can be useful feel free to share here

**Comment by FalsinSoft** [comment]
By the way which Android emulator are you using in the screenshot you posted? It doesn't look the standard one provided with Android SDK...

**Comment by ssakone** [comment]
No its QtSrcpy, i use my phone

**Comment by ssakone** [comment]
[https://github.com/barry-ran/QtScrcpy](https://github.com/barry-ran/QtScrcpy)

**Comment by FalsinSoft** [comment]
Thank you, look really interesting and I'll give it a check as soon as I'll have time. In the meanwhile if you are if you are satisfied in compiling with cmake please close this issue. Thank you
