### ISSUE TITLE
[Feature Request] rewarded interstitial ad units

### ISSUE THREAD

**Issue by zlutor** [FalsinSoft/QtAndroidTools#33]
Is there any plan to support the new [rewarded interstitial ad units](https://support.google.com/admob/answer/9884467) format?
thx in advance!

**Comment by FalsinSoft** [comment]
Yes but I can't give you a timeline since I work on this project when I have some free time than I don't know when the change will be ready, sorry for that...

**Comment by zlutor** [comment]
perfect answer - your time, your priorities!
thx for providing what you have already provided!

I will take it into use idSoft way: "When it is done!" :D

**Comment by FalsinSoft** [comment]
By the way I just noted the new format is still in beta. Before porting I want to wait the final stable release because API can change from beta to final release.
