### ISSUE TITLE
AudioFocus.cpp calls incorrect/nonexistent java method abandonAudioFocus() instead of abandonFocus()

### ISSUE THREAD

**Issue by NielsMayer** [FalsinSoft/QtAndroidTools#36]
Note that an incorrect call to nonexistent Java call abandonAudioFocus() causes the following output

```
W System.err: java.lang.NoSuchMethodError: no non-static method "L.....AndroidAudio;.abandonAudioFocus()V"
W System.err: 	at org.qtproject.qt.android.QtNative.startQtApplication(Native Method)
W System.err: 	at org.qtproject.qt.android.QtNative$7.run(QtNative.java:622)
W System.err: 	at org.qtproject.qt.android.QtThread$1.run(QtThread.java:25)
W System.err: 	at java.lang.Thread.run(Thread.java:923)
```
Because this line should be calling `abandonFocus()` and not `abandonAudioFocus()` in Java:

https://github.com/FalsinSoft/QtAndroidTools/blob/261d732f5eea870858b3031f293523a9eec890a7/QtAndroidTools/QAndroidAudio.cpp#L106

Here is the Java it is attempting to call:

https://github.com/FalsinSoft/QtAndroidTools/blob/261d732f5eea870858b3031f293523a9eec890a7/QtAndroidTools/src/com/falsinsoft/qtandroidtools/AndroidAudio.java#L71

**Comment by FalsinSoft** [comment]
Hi
Thank you for the report. I'll fix when possible. Unfortunately it's a bad period now and can not work on it, sorry...

**Comment by FalsinSoft** [comment]
Fix done, thank you!
