### ISSUE TITLE
Qt 6.4.2 - app always crashes at startup

### ISSUE THREAD

**Issue by zlutor** [FalsinSoft/QtAndroidTools#38]
logcat gives following error: 

`--------- beginning of crash
01-16 19:47:28.504  9710  9710 E AndroidRuntime: FATAL EXCEPTION: main
01-16 19:47:28.504  9710  9710 E AndroidRuntime: Process: com.forfictionmobile...., PID: 9710
01-16 19:47:28.504  9710  9710 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException:
01-16 19:47:28.504  9710  9710 E AndroidRuntime:
01-16 19:47:28.504  9710  9710 E AndroidRuntime: ******************************************************************************
01-16 19:47:28.504  9710  9710 E AndroidRuntime: * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
01-16 19:47:28.504  9710  9710 E AndroidRuntime: * should follow the instructions here:                                       *
01-16 19:47:28.504  9710  9710 E AndroidRuntime: * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
01-16 19:47:28.504  9710  9710 E AndroidRuntime: * to add a valid App ID inside the AndroidManifest.                          *
01-16 19:47:28.504  9710  9710 E AndroidRuntime: * Google Ad Manager publishers should follow instructions here:              *
01-16 19:47:28.504  9710  9710 E AndroidRuntime: * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
01-16 19:47:28.504  9710  9710 E AndroidRuntime: ******************************************************************************
01-16 19:47:28.504  9710  9710 E AndroidRuntime:
01-16 19:47:28.504  9710  9710 E AndroidRuntime:
01-16 19:47:28.504  9710  9710 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:6266)
01-16 19:47:28.504  9710  9710 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5829)
01-16 19:47:28.504  9710  9710 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5737)
01-16 19:47:28.504  9710  9710 E AndroidRuntime:        at android.app.ActivityThread.-wrap1(Unknown Source:0)
01-16 19:47:28.504  9710  9710 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
01-16 19:47:28.504  9710  9710 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
01-16 19:47:28.504  9710  9710 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
01-16 19:47:28.504  9710  9710 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6518)
01-16 19:47:28.504  9710  9710 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-16 19:47:28.504  9710  9710 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
01-16 19:47:28.504  9710  9710 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
01-16 19:47:28.504  9710  9710 E AndroidRuntime: Caused by: java.lang.IllegalStateException:
01-16 19:47:28.504  9710  9710 E AndroidRuntime:
01-16 19:47:28.504  9710  9710 E AndroidRuntime: ******************************************************************************
01-16 19:47:28.504  9710  9710 E AndroidRuntime: * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
01-16 19:47:28.504  9710  9710 E AndroidRuntime: * should follow the instructions here:                                       *
01-16 19:47:28.504  9710  9710 E AndroidRuntime: * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
01-16 19:47:28.504  9710  9710 E AndroidRuntime: * to add a valid App ID inside the AndroidManifest.                          *
01-16 19:47:28.504  9710  9710 E AndroidRuntime: * Google Ad Manager publishers should follow instructions here:              *
01-16 19:47:28.504  9710  9710 E AndroidRuntime: * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
01-16 19:47:28.504  9710  9710 E AndroidRuntime: ******************************************************************************
01-16 19:47:28.504  9710  9710 E AndroidRuntime:
01-16 19:47:28.504  9710  9710 E AndroidRuntime:
01-16 19:47:28.504  9710  9710 E AndroidRuntime:        at com.google.android.gms.internal.ads.zzzx.attachInfo(com.google.android.gms:play-services-ads-lite@@19.8.0:31)
01-16 19:47:28.504  9710  9710 E AndroidRuntime:        at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@19.8.0:3)
01-16 19:47:28.504  9710  9710 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:6263)
01-16 19:47:28.504  9710  9710 E AndroidRuntime:        ... 10 more`

after checking the mentioned link I figured out the reason: missing app id in manifest:
`<manifest>
    <application>
        
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>
    </application>
</manifest>`

I think it might worth mentioning it in the documentation...

**Comment by FalsinSoft** [comment]
This is the reasons for each tool in the library I linked the official google android page in the documentation and expressly ask to read it to understand how to use the feature. The android requirements continuously change and it would be impossible for me to keep updated my documentation...

**Comment by zlutor** [comment]
OK, my bad - I have to admit I have not read it carefully enough then... :(

On the other hand I think this one worth direct mention beside needed permissions for ads. that would saved me some time... ;)
anyway, thx for your work!
