### ISSUE TITLE
[Feature Request] MediaSession API integration

### ISSUE THREAD

**Issue by Allstar12345** [FalsinSoft/QtAndroidTools#39]
API to access a Android MediaSession would be very useful, any Qt App that plays Media could use it as we are well behind Native Android Apps in this regard.

Media Session is responsible for the Media Controls Notification (Or Little card in 12 +), there is a codereview at Qt dev but it's been silent since June 22, the code could be based off that:

https://codereview.qt-project.org/c/qt/qtmultimedia/+/397605

Thanks!

**Comment by FalsinSoft** [comment]
Hi

This feature is useful only for a player applications that is not my case currently than I don't think to add it soon. I'm sorry.

**Comment by Allstar12345** [comment]
No problem, thank you for replying.
