### ISSUE TITLE
Sample banner's ad unit works but my app's ad unit doesn't work

### ISSUE THREAD

**Issue by edips** [FalsinSoft/QtAndroidTools#4]
Hi. I used QtFirebase last year but this year it doesn't work so I think to use Admob without Firebase. I unlinked my ads from Firebase. While testing QtAndroidTools's banner, my app's ad unit doesn't work. Is it required to add app id to AndroidManifest.xml?

```
<meta-data
                    android:name="com.google.android.gms.ads.APPLICATION_ID"
                    android:value="ca-app-pub-3940256099942544~3347511711/>
```

**Comment by FalsinSoft** [comment]
Hi
No, is not required. But are you sure you used the correct ad unit id? In your snippet you used the code containing the "~" as separator, but the correct one is the unit id with the "/" as separator. Check better the admob console for verify...

**Comment by edips** [comment]
My ad ids didn't work maybe because of FireBase so I created a new ad unit id from Admob yesterday and I used it like:
```
QtAndroidAdMobBanner {
        id: banner2
        Layout.alignment: Qt.AlignTop
        unitId: "ca-app-pub-3207315695672286/5123160248"
        type: QtAndroidAdMobBanner.TYPE_BANNER
    }
```
It didn't work again and the log message is :
```
I Ads     : Use AdRequest.Builder.addTestDevice("500768E4EDC7318041A940462B7751F6") to get test ads on this device.
D AudioManager: getStreamVolume isRestricted mode = 0
D AudioManager: getStreamVolume isRestricted mode = 0
I Ads     : Ad failed to load : 3
```
Yesterday it was working, I don't know why it doesn't work for now. I tried it on a few projects. It only works for test ad unit id. 
I used `android:value="ca-app-pub-3940256099942544~3347511711"` in ANdroidManifest.xml because google recommended in [here](https://developers.google.com/admob/android/quick-start).

**Comment by FalsinSoft** [comment]
Is use the code in all my projects and it work as expected without add the tags into AndroidManifest.xml. Have you tried to put your unit id code in the demo app? I don't know if google check if the code will correspond to the app but it would be a good test. By the way, if you don't have any particular reasons to use the normnale banner, is always better to use TYPE_SMART_BANNER.

**Comment by edips** [comment]
I also tested from demo app, my banner looks Loaded but it looks empty. It gave the same log messages like I `Ads     : Ad failed to load : 3` for my banner. Other test banner works. My apps's ads works from Play Store but now I don't make them work in development. I tested again with TYPE_SMART_BANNER it was the same. Well maybe the problem about my banners.

![Screenshot_2019-05-01-19-22-44-731_com falsinsoft QtAndroidToolsDemo](https://user-images.githubusercontent.com/3856713/57027999-8f591000-6c46-11e9-87b3-41d76319e7a3.png)

**Comment by FalsinSoft** [comment]
Once it happened a similar problem to me too, but the problem was connected to one product banner only, not all others of my apps. The day after the banner start working again. In which plaftorm are you testing the banner, emulator of phisical device? And in case using which version of android?

**Comment by edips** [comment]
I use physical device . İt was very weird my banners worked using your project yesterday, but now it doesn't work. The phone has Android 8.0.

**Comment by FalsinSoft** [comment]
Have you tried in the emulator? You don't see your real banner cause emulator change it using a demo banner but at least you can check if the banner load correctly.

**Comment by edips** [comment]
Unfortunately I use Qt on VirtualBox. Emulator doesn't work on VirtualBox because of 3D opengl issue.

**Comment by FalsinSoft** [comment]
Teste your unid id code (ca-app-pub-3207315695672286/5123160248) using demo app in a phisical device. In the beginning both banners (your banner and the demo smart banner) show me load error 3 but after a second show the loaded status. The demo banner show but your banner remained blank. However if you recently created the admob unit id this is normal cause it need some days to show a valid banner.

**Comment by edips** [comment]
Yes I got it thank you for your time. I created the banner yesterday. I also tested my banners which are linked to Firebase. Maybe Firebase banners aren't shown because there is not Firebase SDK. Ok the solution is to wait for a few days.

**Comment by edips** [comment]
I read stackoverflow, someone recommend to reset advertising from device's settings -> Google -> Ads -> Reset advertising ID after resetting this, my ads works :) Thanks!

**Comment by edips** [comment]
Well I had problem with displaying ads again. Now I looked Ionic's AdmobPlus project's issues, someone suggested to deploy app with "signed" mode on [here](https://github.com/admob-plus/admob-plus/issues/51#issuecomment-444868490). It may help if someone has this problem.
