### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.falsinsoft.qtandroidtools.AndroidTools"

### ISSUE THREAD

**Issue by zlutor** [FalsinSoft/QtAndroidTools#40]
I've tried to integrate Qt6 (6.4.2) + CMAKE version into an old app of mine but no success with displaying ads. It works fine with Qt5 or Qt6 + qmake...

I have to admit I'm newbie with CMAKE thus I tried to run QtAndroidToolsDemo, too - failed again with logs below:

`W System  : ClassLoader referenced unknown path:
W linker  : "/data/app/org.qtproject.example.QtAndroidToolsDemo-OZ2UfDfux5ValhpZcPT42Q==/lib/arm64/libc++_shared.so" unused DT entry: type 0x70000001 arg 0x0
I QtCore  : Start
I Qt      : qt started
D OpenGLRenderer: HWUI GL Pipeline
I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 05/10/18, 624c5bb, I109c45a694
D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
I zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
I OpenGLRenderer: Initialized EGL, version 1.4
D OpenGLRenderer: Swap behavior 2
W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
D vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
W System.err: java.lang.ClassNotFoundException: Didn't find class "com.falsinsoft.qtandroidtools.AndroidTools" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /system/vendor/lib64]]
W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W System.err: 	at org.qtproject.qt.android.QtNative.startQtApplication(Native Method)
W System.err: 	at org.qtproject.qt.android.QtNative$7.run(QtNative.java:622)
W System.err: 	at org.qtproject.qt.android.QtThread$1.run(QtThread.java:25)
W System.err: 	at java.lang.Thread.run(Thread.java:764)
W libEGL  : EGLNativeWindowType 0x7bed0fd010 disconnect failed`

Could you, please, give some hint how can I get them running?
Thx, Zoltan

**Comment by FalsinSoft** [comment]
Hi
To be honest I'm not very familiar with cmake either. I'll check all the cmake files since I need to move my projects too cause Qt 6 doesn't support anymore creation of android abi using qmake... :-(

**Comment by FalsinSoft** [comment]
After checked the QtAdroidToolsDemo compile using cmake without errors. In which phase do you receive the error?

**Comment by zlutor** [comment]
I got it during application startup...

**Comment by FalsinSoft** [comment]
Probably found the problem but need some time to fix cause I discovered some admob code is deprecated and needs to be updated...

**Comment by zlutor** [comment]
Great news! Take your time, I will not be able to return to my prt projec before weekend...
BTW. I tried to.upgrade to lates google stupp but there were lots of complation errors in your code tuen. Have you found the same way hing?

**Comment by FalsinSoft** [comment]
I found for example that InterstitialAd needs to be updated to new syntax. Didn't check other errors since this is the first problem to start from and, once fixed, move on...

**Comment by FalsinSoft** [comment]
I still need to fix RewardedAd but if you don't use this ad tool check the last commit to cmake projects file and import the changes. This should fix the problem. Basically the java file was not copied in the android app folder.

**Comment by zlutor** [comment]
I use rewarded video ad, so I wait for fix that too.
thx for dealing qith itwill

**Comment by FalsinSoft** [comment]
Just pushed the complete working version. Please note that the RewardedVideo is now RewardedAd following Google specifications. I didn't updated the documentation yet than check the example qml to know what is changed in the interface.

**Comment by zlutor** [comment]
I try to build the things, demo sw built with no error but my own app has such errors:

`> Task :compileReleaseJavaWithJavac
<cutcut>\android-build\src\com\falsinsoft\qtandroidtools\AndroidAdMobInterstitial.java:29: error: cannot find symbol
import com.google.android.gms.ads.InterstitialAd;
                                 ^
  symbol:   class InterstitialAd
  location: package com.google.android.gms.ads
<cutcut>\android-build\src\com\falsinsoft\qtandroidtools\AndroidAdMobInterstitial.java:46: error: cannot find symbol
    private InterstitialAd mInterstitialAd = null;
            ^
  symbol:   class InterstitialAd
  location: class AndroidAdMobInterstitial
<cutcut>\android-build\src\com\falsinsoft\qtandroidtools\AndroidAdMobRewardedVideo.java:29: error: package com.google.android.gms.ads.reward does not exist
import com.google.android.gms.ads.reward.RewardItem;
                                        ^
<cutcut>\android-build\src\com\falsinsoft\qtandroidtools\AndroidAdMobRewardedVideo.java:30: error: package com.google.android.gms.ads.reward does not exist
import com.google.android.gms.ads.reward.RewardedVideoAd;
                                        ^
<cutcut>\android-build\src\com\falsinsoft\qtandroidtools\AndroidAdMobRewardedVideo.java:31: error: package com.google.android.gms.ads.reward does not exist
import com.google.android.gms.ads.reward.RewardedVideoAdListener;
                                        ^`

build.gradle has such lines added:
`dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
//  https://falsinsoft.github.io/QtAndroidTools/Documentation/
    implementation 'com.google.android.gms:play-services-ads:21.+'
    implementation 'androidx.activity:activity:1.5.1'
    implementation 'androidx.fragment:fragment:1.5.5'
    implementation 'androidx.appcompat:appcompat:1.4.2'
}`

something is missing somewhere but cannot catch it...

**Comment by FalsinSoft** [comment]
You still have the old java files. Clean all the compiled parts and be sure to have the new java files under the project android src folder.

**Comment by zlutor** [comment]
that was the reason! I will close this issue thx for proper fixes and especially the help!

**Comment by zlutor** [comment]
still one question rather than comment..

I tried to create some app from scratch and adding new ads. I tried to copy everything from your demo cmake file but for one reason or another java files - e.g. AndroidAdMobRewardedAd.java - are not copied into the android/src/com/falsinsoft/qtandroidtools folder of my application. They are copied there in your demo app...

what did I do wrong? thx

**Comment by FalsinSoft** [comment]
Sorry, too little information to understand the problem. Can you send me (by email) your app project to allow me check it?

**Comment by zlutor** [comment]
Hi,

I hope you get thie email...

Should I send the Cmake file?

Thx,

Zoltan

**Comment by zlutor** [comment]
> Sorry, too little information to understand the problem. Can you send me (by email) your app project to allow me check it?

try to clarify...

have a project trying to use QtAndroidTools for displaying ads. I tried to be inspired by cmake file of DemoTools but my app is being ported from Qt5 and cmake file was generated by the suggested Qt Python script is was not that trivial (for me).

I've got my app compiled somehow at the end of the day but there was runtime error about missing classes related to AdMob ads (interstitial and video what I used). After spending some time I figured out the root cause of the problem is that those java files are not copied into /android/src/com/falsinsoft/qtandroidtools folder of my app - as they are in the Demo Tools - thus copied them with hand and then no missing classes and I see ads in my app...

I was not able to figure out what the heck is missing from my - or QtAndroidTool(?) cmake - that would copy all relevant java files into /android/src/com/falsinsoft/qtandroidtools of my own application based on activated features (ads, etc.)

**Comment by FalsinSoft** [comment]
Well, best solution would be to have the entire project to compile to allow me to check the problem. However if you don't want to share the source of your app send me (or copy here) the content of your cmake project file.

**Comment by zlutor** [comment]
cmake_minimum_required(VERSION 3.19)
project(my-application VERSION 1.0 LANGUAGES CXX)

set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_INCLUDE_CURRENT_DIR ON)

find_package(QT NAMES Qt5 Qt6 REQUIRED COMPONENTS Core)
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Gui Multimedia Quick QuickControls2 Svg)

qt_standard_project_setup()

qt_add_executable(my-application
    main.cpp
)

target_link_libraries(my-application PRIVATE
    Qt::Core
    Qt::Gui
    Qt::Multimedia
    Qt::Quick
    Qt::QuickControls2
    Qt::Svg
)

set(qml_resource_files
    "main.qml"
)

qt_add_resources(my-application "qml"
    PREFIX
    "/"
    FILES
    ${qml_resource_files}
)

set(audio_resource_files
    "audio/xxx.mp3"
)

qt_add_resources(my-application "audio"
    PREFIX
    "/"
    FILES
    ${audio_resource_files}
)

set(visuals_resource_files
    "visuals/house-ads/icon10-512x512 - catch.png"
    "visuals/house-ads/icon10-512x512 - elevate.png"
    "visuals/house-ads/icon10-512x512 - piece.png"
)

qt_add_resources(my-application "visuals"
    PREFIX
    "/"
    FILES
    ${visuals_resource_files}
)

if(ANDROID)
    set_property(TARGET my-application APPEND PROPERTY QT_ANDROID_PACKAGE_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/android)
    add_custom_target(Android SOURCES
        android/AndroidManifest.xml
        android/build.gradle
        android/gradle.properties
    )

    #    set(QTAT_APP_PERMISSIONS ON)
    #    set(QTAT_APK_INFO ON)
    #    set(QTAT_SCREEN ON)
    #    set(QTAT_SYSTEM ON)
    #    set(QTAT_BATTERY_STATE ON)
    #    set(QTAT_SIGNAL_STRENGTH ON)
    #    set(QTAT_IMAGES ON)
    #    set(QTAT_NOTIFICATION ON)
    set(QTAT_ADMOB_BANNER ON)
    set(QTAT_ADMOB_INTERSTITIAL ON)
    set(QTAT_ADMOB_REWARDED_AD ON)
    #    set(QTAT_PLAY_STORE ON)
    #    set(QTAT_GOOGLE_ACCOUNT ON)
    #    set(QTAT_GOOGLE_DRIVE ON)
    #    set(QTAT_SHARING ON)
    #    set(QTAT_USER_MESSAGING_PLATFORM ON)
    #    set(QTAT_AUDIO ON)
    add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/QtAndroidTools/QtAndroidTools build)
    include_directories(${CMAKE_CURRENT_SOURCE_DIR}/QtAndroidTools/QtAndroidTools)
    target_link_libraries(my-application PRIVATE QtAndroidTools)
    set(QT_ANDROID_PACKAGE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/android")
endif()

qt_generate_deploy_app_script(
    TARGET my-application
    FILENAME_VARIABLE deploy_script
    NO_UNSUPPORTED_PLATFORM_ERROR
)

install(SCRIPT ${deploy_script})`

**Comment by FalsinSoft** [comment]
Are you sure this path is correct "QtAndroidTools/QtAndroidTools"? It seems a bit strange... you put the QtAndroidTools package folder inside a parent folder with same name?

**Comment by zlutor** [comment]
yes, that is correct! I added your git repo as subproject into mine and this is your folder structure: 
_crossplatform\my-applciation\QtAndroidTools\QtAndroidTools

**Comment by FalsinSoft** [comment]
I'm quite new to cmake too but an idea could be to move up the _set(QT_ANDROID_PACKAGE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/android")_ command like this:

set(QT_ANDROID_PACKAGE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/android")
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/QtAndroidTools/QtAndroidTools)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/QtAndroidTools/QtAndroidTools build)
target_link_libraries(my-application PRIVATE QtAndroidTools)

**Comment by zlutor** [comment]
> include_directories(${CMAKE_CURRENT_SOURCE_DIR}/QtAndroidTools/QtAndroidTools)
> add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/QtAndroidTools/QtAndroidTools build)
> target_link_libraries(my-application PRIVATE QtAndroidTools)

thank you very much, it works!

**Comment by FalsinSoft** [comment]
So it seems cmake execute instructions sequentially. In your case you asked to cmake to process the QtAndroidTools cmake file before set the android folder path where to copy java files to...

**Comment by zlutor** [comment]
Oh, I see...

Thx again!
