### ISSUE TITLE
copy&paste error in 

### ISSUE THREAD

**Issue by zlutor** [FalsinSoft/QtAndroidTools#41]
There is a [copy&paste error in CMakeList.txt ](https://github.com/FalsinSoft/QtAndroidTools/blob/master/QtAndroidTools/CMakeLists.txt#L100)file on master branch related to rewarded video ad support - it depends on _**QTAT_ADMOB_INTERSTITIAL**_ - and a typo QTAT_ADMOB_REWA**_REDED_**_VIDEO :
`option(QTAT_ADMOB_REWAREDED_VIDEO "Enable QtAndroidTools AdMob Rewareded Video.")
if(QTAT_ADMOB_INTERSTITIAL)
	add_compile_definitions(QTAT_ADMOB_REWAREDED_VIDEO)
	list(APPEND QTAT_SOURCE_FILES QAndroidAdMobRewardedVideo.cpp)
	list(APPEND QTAT_HEADER_FILES QAndroidAdMobRewardedVideo.h)
	list(APPEND QTAT_JAVA_FILES
		${QTAT_JAVA_DIR}/AndroidAdMob.java
		${QTAT_JAVA_DIR}/AndroidAdMobRewardedVideo.java
		${QTAT_JAVA_DIR}/SyncRunOnUiThread.java)
endif()`

here it is the fix for it:
```
diff --git a/QtAndroidTools/CMakeLists.txt b/QtAndroidTools/CMakeLists.txt
index fe6d69f..594db28 100644
--- a/QtAndroidTools/CMakeLists.txt
+++ b/QtAndroidTools/CMakeLists.txt
@@ -96,9 +96,9 @@ if(QTAT_ADMOB_INTERSTITIAL)
 		${QTAT_JAVA_DIR}/SyncRunOnUiThread.java)
 endif()
 
-option(QTAT_ADMOB_REWAREDED_VIDEO "Enable QtAndroidTools AdMob Rewareded Video.")
-if(QTAT_ADMOB_INTERSTITIAL)
-	add_compile_definitions(QTAT_ADMOB_REWAREDED_VIDEO)
+option(QTAT_ADMOB_REWARDED_VIDEO "Enable QtAndroidTools AdMob Rewareded Video.")
+if(QTAT_ADMOB_REWARDED_VIDEO)
+        add_compile_definitions(QTAT_ADMOB_REWARDED_VIDEO)
 	list(APPEND QTAT_SOURCE_FILES QAndroidAdMobRewardedVideo.cpp)
 	list(APPEND QTAT_HEADER_FILES QAndroidAdMobRewardedVideo.h)
 	list(APPEND QTAT_JAVA_FILES
```

**Comment by FalsinSoft** [comment]
Fixed and just updated the repository. Thank you

**Comment by zlutor** [comment]
ooops. there is one left! :D
[
Rewarded ad is still depends on interstitial](https://github.com/FalsinSoft/QtAndroidTools/blob/master/QtAndroidTools/CMakeLists.txt#L100)...

instead of if(**_QTAT_ADMOB_REWARDED_VIDEO_**)...

**Comment by FalsinSoft** [comment]
Fixed and updated. Sorry for these error but it's not me who created this config file. They were created by another person who contributed to the project....

**Comment by zlutor** [comment]
there is nothing to say sorry for! I have to say thank you all making these tools available!

as my grandpa used to say: the only one who makes no making mistakes ever is the one who does not do anything...
