### ISSUE TITLE
Can't find QtAndroidTools::InitializeQmlTools();

### ISSUE THREAD

**Issue by Shell-reversecpp** [FalsinSoft/QtAndroidTools#43]

**Comment by FalsinSoft** [comment]
Can you compile the demo android app?

**Comment by Shell-reversecpp** [comment]
> Can you compile the demo android app? 
I tried but it failed.
I have my project and i compiled this lib and get libQtAndroidTools.a. I added folder QtAndroidTools folder to my project. 

Here my AndroidTools.pri 

`
QT_ANDROID_TOOLS_LIBDIR = /home/snake0x8/Документы/QtProgets/GigaGain/


QT_ANDROID_TOOLS_INCLUDE = /home/snake0x8/Документы/QtProgets/GigaGain/QtAndroidTools/


INCLUDEPATH += $$QT_ANDROID_TOOLS_INCLUDE


LIBS += -L$$QT_ANDROID_TOOLS_LIBDIR -lQtAndroidTools


INCLUDEPATH += $$QT_ANDROID_TOOLS_INCLUDE `


Here is my .pro
`ANDROID_PACKAGE_SOURCE_DIR = $$PWD/android

resources.prefix = /$${TARGET}
HEADERS += \
    mainfield.h \
    $$QT_ANDROID_TOOLS_INCLUDE/home/snake0x8/Документы/QtProgets/GigaGain/

SOURCES += \
    main.cpp \
    mainfield.cpp

resources.files = main.qml

RESOURCES += resources \
    res.qrc

DEFINES += \
    QTAT_APP_PERMISSIONS \
    QTAT_APK_EXPANSION_FILES \
    QTAT_APK_INFO \
    QTAT_SCREEN \
    QTAT_SYSTEM \
    QTAT_BATTERY_STATE \
    QTAT_SIGNAL_STRENGTH \
    QTAT_IMAGES \
    QTAT_NOTIFICATION \
    QTAT_ADMOB_BANNER \
    QTAT_ADMOB_INTERSTITIAL \
    QTAT_ADMOB_REWARDED_VIDEO \
    QTAT_PLAY_STORE \
    QTAT_GOOGLE_ACCOUNT \
    QTAT_GOOGLE_DRIVE \
    QTAT_SHARING \
    QTAT_USER_MESSAGING_PLATFORM

DISTFILES += \
    QtAndroidTools.pri \
    android/AndroidManifest.xml \
    android/build.gradle \
    android/gradle.properties \
    android/gradle/wrapper/gradle-wrapper.jar \
    android/gradle/wrapper/gradle-wrapper.properties \
    android/gradlew \
    android/gradlew.bat \
    android/res/values/libs.xml

include(QtAndroidTools/QtAndroidTools.pri)
`


I fixed previous mistake but i have new.  error: undefined symbol: AndroidBitmap_getInfo , /home/snake0x8/QtAndroidTools/QtAndroidTools/QtAndroidTools.cpp:198: referenced by QtAndroidTools.cpp:198 (/home/snake0x8/QtAndroidTools/QtAndroidTools/QtAndroidTools.cpp:198)  ,  error: undefined symbol: AndroidBitmap_lockPixels,  ошибка: error: undefined symbol: AndroidBitmap_unlockPixels.

**Comment by FalsinSoft** [comment]
At first you need to be sure you can compile the demo app. If you can't compile it means your environment is not correct. What errors do you have when try compile the demo app?

**Comment by Shell-reversecpp** [comment]
> At first you need to be sure you can compile the demo app. If you can't compile it means your environment is not correct. What errors do you have when try compile the demo app?
(I use gradle-8.0.2-1)

Warning: QML import could not be resolved in any of the import paths: QtAndroidTools

AILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':packageDebug'.
> Could not create task ':processDebugResources'.
   > Cannot use @TaskAction annotation on method IncrementalTask.taskAction$gradle_core() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Building the android package failed!
  -- For more information, run this command with --verbose.

**Comment by FalsinSoft** [comment]
Gradle version to use is inside the build.grandle project file. In the demo app the version required is 7.2.1 so how is possible you are using version 8? You need to try compile the demo app as is without any change to do a correct test

**Comment by Shell-reversecpp** [comment]
> Gradle version to use is inside the build.grandle project file. In the demo app the version required is 7.2.1 so how is possible you are using version 8? You need to try compile the demo app as is without any change to do a correct test

Sorry for misunderstanding , I thought that project uses's  my system Gradle but why I have this mistake  with build
 
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':packageDebug'.
> Could not create task ':processDebugResources'.
   > Cannot use @TaskAction annotation on method IncrementalTask.taskAction$gradle_core() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Building the android package failed!
  -- For more information, run this command with --verbose.

**Comment by Shell-reversecpp** [comment]
> Gradle version to use is inside the build.grandle project file. In the demo app the version required is 7.2.1 so how is possible you are using version 8? You need to try compile the demo app as is without any change to do a correct test

sorry for misunderstanding , i thought that project uses's my system gradle. I fixed problem and build the demo project. What will be the next step to use this lib in my project ?

**Comment by FalsinSoft** [comment]
At first select the tools you need. In your project file you import all the tools, do you need all? Then read to documentation to include the library in your project.

**Comment by Shell-reversecpp** [comment]
> At first select the tools you need. In your project file you import all the tools, do you need all? Then read to documentation to include the library in your project.

My project needs all components, maybe except for QTAT_GOOGLE_DRIVE, but it's not necessary right now.
I aslo have libQtAndroidToolsDemo_arm64-v8a.so after build and QtAndroidTools documentation  have few instructions for installation This includes a few suggestions for adding a lib to the .pro file but does not include the compilation steps for the library and the name that should be generated if it builds correctly.

 . Furthermore I have this build error in my project. 
ld: error: undefined symbol: AndroidBitmap_getInfo
>>> referenced by QtAndroidTools.cpp:198 (/home/snake0x8/QtAndroidTools/QtAndroidTools/QtAndroidTools.cpp:198)
>>>               QtAndroidTools.cpp.o:(QtAndroidTools::imageToAndroidBitmap(QImage const&)) in archive /home/snake0x8/Документы/QtProgets/GigaGain/libQtAndroidTools.a
>>> referenced by QtAndroidTools.cpp:230 (/home/snake0x8/QtAndroidTools/QtAndroidTools/QtAndroidTools.cpp:230)
>>>               QtAndroidTools.cpp.o:(QtAndroidTools::androidBitmapToImage(QJniObject const&)) in archive /home/snake0x8/Документы/QtProgets/GigaGain/libQtAndroidTools.a

ld: error: undefined symbol: AndroidBitmap_lockPixels
>>> referenced by QtAndroidTools.cpp:205 (/home/snake0x8/QtAndroidTools/QtAndroidTools/QtAndroidTools.cpp:205)
>>>               QtAndroidTools.cpp.o:(QtAndroidTools::imageToAndroidBitmap(QImage const&)) in archive /home/snake0x8/Документы/QtProgets/GigaGain/libQtAndroidTools.a
>>> referenced by QtAndroidTools.cpp:252 (/home/snake0x8/QtAndroidTools/QtAndroidTools/QtAndroidTools.cpp:252)
>>>               QtAndroidTools.cpp.o:(QtAndroidTools::androidBitmapToImage(QJniObject const&)) in archive /home/snake0x8/Документы/QtProgets/GigaGain/libQtAndroidTools.a

ld: error: undefined symbol: AndroidBitmap_unlockPixels
>>> referenced by QtAndroidTools.cpp:218 (/home/snake0x8/QtAndroidTools/QtAndroidTools/QtAndroidTools.cpp:218)
>>>               QtAndroidTools.cpp.o:(QtAndroidTools::imageToAndroidBitmap(QImage const&)) in archive /home/snake0x8/Документы/QtProgets/GigaGain/libQtAndroidTools.a
>>> referenced by QtAndroidTools.cpp:267 (/home/snake0x8/QtAndroidTools/QtAndroidTools/QtAndroidTools.cpp:267)
>>>               QtAndroidTools.cpp.o:(QtAndroidTools::androidBitmapToImage(QJniObject const&)) in archive /home/snake0x8/Документы/QtProgets/GigaGain/libQtAndroidTools.a
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:359: libGigaGain_arm64-v8a.so] Error 1

**Comment by FalsinSoft** [comment]
If you have a basic knowledge about how cmake system work (not qmake, it has been deprecated, which version of the library are you using?) the instruction provided are enough. The library cmake file generate a static library than you can not see as .so in your project. The linker error you see means compiler doesn't find  jnigraphics native library from Android ndk.

**Comment by Shell-reversecpp** [comment]
> If you have a basic knowledge about how cmake system work (not qmake, it has been deprecated, which version of the library are you using?) the instruction provided are enough. The library cmake file generate a static library than you can not see as .so in your project. The linker error you see means compiler doesn't find jnigraphics native library from Android ndk.

i'm pretty familiar with cmake but your library is not built normally we need to build with root user , obligatory with Qt environment due to need to use compiler under android. Clarify the question, I'm using Qt 6.5 and the library from this git. This is a small example of what a complete installation instruction looks like.

`Building
Configuring

Enter the repository clone and create a building directory there. The name of the directory doesn't matter, e.g. bin or build (bin will be used for the rest of this documentation to refer to this directory). An example for creating the directory and entering it for the terminal:

cd xray-16 && mkdir bin && cd bin

Once you're inside of bin, configure the project by running:

    For Debian/Ubuntu

cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_BINDIR=/usr/games

    For Fedora/CentOS

cmake .. -DCMAKE_INSTALL_LIBDIR=lib64 -DCMAKE_INSTALL_PREFIX=/usr

    For ArchLinux/Manjaro

cmake .. -DCMAKE_INSTALL_PREFIX=/usr

! If you plan to build a package, go to [Installing](https://github.com/OpenXRay/xray-16/wiki/%5BEN%5D-How-to-build-and-setup-on-Linux#installing) now.

    For a portable installation (Use these instructions if you don't want to install the engine system-wide)

cmake ..`

**Comment by FalsinSoft** [comment]
All the project is designed to be compiled using QtCreator, also under Linux without root privileges so if you want to use it in your "custom" project without any help of the ide I'm sorry but never try it (I develop under Windows) and I cannot help you in this phase.

**Comment by Shell-reversecpp** [comment]
> All the project is designed to be compiled using QtCreator, also under Linux without root privileges so if you want to use it in your "custom" project without any help of the ide I'm sorry but never try it (I develop under Windows) and I cannot help you in this phase.

I apologize for the confusion. I'm working on building a project using Manjaro Linux, and I followed your suggestion to use the QtAndroidToolsDemo. However, I encountered an error during the build process.


FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':packageDebug'.
> Could not create task ':mergeDebugAssets'.
   > Cannot use @TaskAction annotation on method IncrementalTask.taskAction$gradle_core() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.

And that's whay root 
DCMAKE_CXX_FLAGS_INIT:STRING=-DQT_QML_DEBUG на /home/snake0x8/QtAndroidTools/build-QtAndroidTools-Android_Qt_6_5_0_Clang_arm64_v8a-Debug.
-- Android: Targeting API '23' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
-- Android: Selected unified Clang toolchain
-- The CXX compiler identification is Clang 14.0.6
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/snake0x8/Android/SDK/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
-- Performing Test HAVE_EGL
-- Performing Test HAVE_EGL - Success
-- Found EGL: /home/snake0x8/Android/SDK/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include (found version "1.5") 
-- Performing Test HAVE_GLESv2
-- Performing Test HAVE_GLESv2 - Success
-- Found GLESv2: /home/snake0x8/Android/SDK/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include  
-- Found WrapVulkanHeaders: /home/snake0x8/Android/SDK/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include  
CMake Error at CMakeLists.txt:172 (configure_file):
  Operation not permitted

**Comment by FalsinSoft** [comment]
Sorry bit I still don't understand if you are trying to compile using your custom cmake on command line or using Qt Creator. Can you do a test using Qt Creator in your system to compile the demo app?

And what is this error?

`CMake Error at CMakeLists.txt:172 (configure_file):`

What is the operation not permitted here? I repeat again, I tested all the project using Qt Creator and I do not guarantee that the project files will work as-is using a different build method...

**Comment by Shell-reversecpp** [comment]
> No I just open Demo project in QtCreator and I try to biuld it. May be to make it easier you could provide step by step(git clone https://github.com/FalsinSoft/QtAndroidTools.git)
 kindly ask if you could provide installation instructions for your library in a step-by-step manner for me and other users who will try to use it. This is how developers usually do it, and it saves time and nerves. I have encountered some errors, and I'm not sure if I'm doing everything correctly. Therefore, clear instructions starting from downloading the repository files would help to understand how it should be done.

**Comment by FalsinSoft** [comment]
At first you must to be sure to compile correctly the demo app using Qt Creator. If you can not compile means your environment is not correct and in this case it's useless to go on. Instruction to install is basically copy the QtAndroidTools where do you prefer inside your project folders and set the correct corresponding path in your project CMakeList.txt to point the library folder as follow:

   ```
    set(QTAT_APP_PERMISSIONS ON)
    set(QTAT_APK_INFO ON)
    set(QTAT_SCREEN ON)
    set(QTAT_SYSTEM ON)
    set(QTAT_BATTERY_STATE ON)
    set(QTAT_SIGNAL_STRENGTH ON)
    set(QTAT_IMAGES ON)
    set(QTAT_NOTIFICATION ON)
    set(QTAT_ADMOB_BANNER ON)
    set(QTAT_ADMOB_INTERSTITIAL ON)
    set(QTAT_ADMOB_REWARDED_AD ON)
    set(QTAT_PLAY_STORE ON)
    set(QTAT_GOOGLE_ACCOUNT ON)
    set(QTAT_GOOGLE_DRIVE ON)
    set(QTAT_SHARING ON)
    set(QTAT_USER_MESSAGING_PLATFORM ON)
    set(QTAT_AUDIO ON)
    set(QT_ANDROID_PACKAGE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/android")
    include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../QtAndroidTools)
    add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../QtAndroidTools build)
    target_link_libraries(your_project_name PRIVATE QtAndroidTools)
```

Finished. it doesn't seem so difficult, it's all "written" in the CMakeList.txt of the demo project. If you really are confident with cmake file you shouldn't have a problem figuring it out.
