### ISSUE TITLE
QtAndroidImages.getAlbumsList() Can not run Android 12

### ISSUE THREAD

**Issue by deletexl** [FalsinSoft/QtAndroidTools#44]
I am developing an application for Android. On devices before Android 12, I can successfully read the images in the gallery, but the Images functions do not work for Android 12 and later.

QtAndroidImages.getAlbumsList() 

The function does not translate anything. I don't think there is a problem with permissions. I tested it on many android 12 devices. You can test it with the emulator. There is no error output. Any idea what is causing the problem?

**Comment by FalsinSoft** [comment]
I'll check about it but I'm really busy right now and I'll need some time, sorry...

**Comment by FalsinSoft** [comment]
Found the problem. Read images need the READ_EXTERNAL_STORAGE permission. Before Android 12 this permission is assigned without need to be requested. On the contrary from Android 12 this permission need to be requested to the user. I added the permission request into the demo tool with the last commit. Please, check it and confirm this solution will work for you too.

**Comment by FalsinSoft** [comment]
Have you tried the suggestion and can confirm is working for you too?
