### ISSUE TITLE
Rewarded Video Ads

### ISSUE THREAD

**Issue by pockemul** [FalsinSoft/QtAndroidTools#5]
Hi,
Do you plan to add Rewarded Video Ads to QtAndroidTools ?

regards

**Comment by FalsinSoft** [comment]
Hi
I don't use it in my project but if you need it I can try to add. Just give me some time cause I'm in a busy period right now... ^_^

**Comment by pockemul** [comment]
Great.
In the mean time i will take a look on your framework and perhaps i will try to implement it.

**Comment by FalsinSoft** [comment]
Don't worry, you don't need to do that if you can wait a little. I hope to start additing this new feature on the next days.

**Comment by pockemul** [comment]
Thx a lot

**Comment by FalsinSoft** [comment]
Just committed the new 1.1 version with the tool for show rewarded video. Please, try it and keep me informed if it work as you expected for close the issue. ^_^

**Comment by pockemul** [comment]
Thank you for this fast implementation.
I just test and i have two issues:
- The video is played but sometimes, the overlay with the countdown is not showing.
- at the end when i close the video, i have a java error: Handler (android.os.Handler) {f717e4f} sending message to a Handler on a dead thread

I will test deeply tomorrow.

regards

**Comment by pockemul** [comment]
I have the video played on a black screen. 
If i put the phone on sleep and wake up it, then the overlay is displayed correctly.
Perhaps, you could take a look on this test app (https://github.com/cuongkjm/TestAdmob) which is working for me. My skills on android are too low to investigate the differences in implementation with QtAndroidTools :-)

**Comment by FalsinSoft** [comment]
Checked the link, basically is the same of mine cause the API for manage rewarded video are very few. Are you testing your project on a physical device or inside the emulator?

**Comment by pockemul** [comment]
I have the issue with the QtAndroidToolsDemo project on both my phone (Redmi note5) and a tablet.
Is it working on your side ?

**Comment by pockemul** [comment]
I have exactly the issue described here in the second video: https://forums.coronalabs.com/topic/75658-admob-rewarded-video-bug/

**Comment by FalsinSoft** [comment]
No, I didn't see this kinf of problem. I tested the tool on an old shartphone and in the emulator also. I can see the final java crash on the log but it seem connected to the internal player used by the admob component. However in all cases the video disappeared and returned correctly to the app. Try o make the test in the emulator also for check if there are differences...

**Comment by pockemul** [comment]
on the simulator on Android 5 it seems to work. 
My phone is on Android 9 and my tablet on Android 8.
I checked 32bits and 64bits.

**Comment by FalsinSoft** [comment]
Regarding the example project you linked the only difference with my demo tool it can come in mind is the difference in google play component used. Inside the _build.gradle_ file of the project, under the section "dependencies" it use the version 17 as follow:

`implementation 'com.google.android.gms:play-services-ads:17.1.1'`

On the contrary mi demo tool still use the version 16. You can try to set the same version and test again in your devices.

**Comment by pockemul** [comment]
Already tried :-) no luck
by the way, I use Qt 5.12.3 

edit: tested on a Samsung Galaxy A5 , android 7 32 bits , it doesn't work.

**Comment by FalsinSoft** [comment]
I found a physical device where I can reproduce the problem. I'll try to investicate on it. Can you confirm the example project you linked [here](https://github.com/cuongkjm/TestAdmob) doesn't show the issue and work as expected?

**Comment by pockemul** [comment]
> I found a physical device where I can reproduce the problem. I'll try to investicate on it. Can you confirm the example project you linked [here](https://github.com/cuongkjm/TestAdmob) doesn't show the issue and work as expected?

Yes I confirm.

**Comment by FalsinSoft** [comment]
Probably found the problem. Try the latest committed version (not tagget yet) and keep me informed. Now it's working as expected in my device.

**Comment by pockemul** [comment]
Well done Master.
It works :-)
Thank you so much
