### ISSUE TITLE
QT version

### ISSUE THREAD

**Issue by Dongbox** [FalsinSoft/QtAndroidTools#6]
**what the version of QT should I use ?**

**Comment by FalsinSoft** [comment]
Currently I use the 5.12.4 version but it should work also with older versions (not too old however).
Why? It there some problem?

**Comment by Dongbox** [comment]
> Currently I use the 5.12.4 version but it should work also with older versions (not too old however).
> Why? It there some problem?

**Yub. I used 5.7.3 version before.It could not run.
The result is "Qt quick" version, So I change the 5.11.1 version now.
But the new problem go on.**
![image](https://user-images.githubusercontent.com/36894425/60384601-6de39b80-9ab2-11e9-9471-814912f0c360.png)
**I guess the problem is the association between gradle version and Android version
How should I solve it?**

**Comment by FalsinSoft** [comment]
google() is a repository name inside gradle file. It seem you are using an old version of gradle that doesn't know this option. You should try the latest version but is there a particular reasons you can not move to the latest version of Qt?

**Comment by Dongbox** [comment]
### **No, I change the repositories.**
![image](https://user-images.githubusercontent.com/36894425/60386064-32050200-9ac3-11e9-8775-58e32832c335.png)
### **And  edit the "gradle-wrapper.properties"** 
![image](https://user-images.githubusercontent.com/36894425/60386083-6f698f80-9ac3-11e9-83dc-c9a590928b52.png)
### **(Because my version of build gradle is 3.2.0.)**
### **Now I come to my last problem.**
![image](https://user-images.githubusercontent.com/36894425/60386112-b5265800-9ac3-11e9-846a-101f6c5f882c.png)
### **How to solve this?**

**Comment by Dongbox** [comment]
![image](https://user-images.githubusercontent.com/36894425/60386340-31219f80-9ac6-11e9-8f1b-f03d455b6530.png)
Lastest!!!!
The app are Flashback.

**Comment by FalsinSoft** [comment]
Try to keep the full apk path more shorter. Android SDK tools can not support path longest than a specific limit (that seem to remember is 256 characters). Change in Qt Creator project settings the apk path, for example not "Android_for_armeabi_v7a_...." but just "Android" and retry...

**Comment by Dongbox** [comment]
Thanks.I try again.

**Comment by FalsinSoft** [comment]
Some news about this issue?

**Comment by Dongbox** [comment]
No,That`s all.  
Thanks a lot, this is my lesson-work.

**Comment by FalsinSoft** [comment]
ok, sorry I couldn't help you more :(
Can I close this issue?
