### ISSUE TITLE
Minimum supported Gradle version

### ISSUE THREAD

**Issue by TechComet** [FalsinSoft/QtAndroidTools#9]
Hi,

Minimum supported Gradle version is 5.4.1. Current version is 4.6. If using the gradle wrapper

**Comment by FalsinSoft** [comment]
Hi
Can you clarify better the problem? I don't understand very well what you mean. gradle file came form the Qt tempolate base.

**Comment by TechComet** [comment]
Gradle version old .. I fix problem
